# Generated by Django 3.2.18 on 2023-05-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
