# Generated by Django 3.2.18 on 2023-09-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
