# Generated by Django 3.2.18 on 2023-05-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='code',
            field=models.FloatField(auto_created=True, default=0.0, unique=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campsites/'),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='price',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='naturalpark',
            name='province',
            field=models.CharField(choices=[(1, 'Buenos Aires'), (2, 'Ciudad Autónoma de Buenos Aires'), (3, 'Catamarca'), (4, 'Chaco'), (5, 'Chubut'), (6, 'Córdoba'), (7, 'Corrientes'), (8, 'Entre Ríos'), (9, 'Formosa'), (10, 'Jujuy'), (11, 'Salta'), (12, 'Tucumán'), (13, 'La Pampa'), (14, 'La Rioja'), (15, 'San Juan'), (16, 'Mendoza'), (17, 'Misiones'), (18, 'Neuquén'), (19, 'Río Negro'), (20, 'San Luis'), (21, 'Santa Cruz'), (22, 'Santa Fé'), (23, 'Santiago del Estero'), (24, 'Tierra del Fuego')], max_length=100),
        ),
        migrations.AlterField(
            model_name='naturalpark',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterModelTable(
            name='availability',
            table='Disponibilidades',
        ),
        migrations.AlterModelTable(
            name='campsite',
            table='Campings',
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categorías',
        ),
        migrations.AlterModelTable(
            name='naturalpark',
            table='Parques_Naturales',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Perfiles',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Reservas',
        ),
    ]
