# Generated by Django 3.2.18 on 2023-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20230515_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalpark',
            name='province',
            field=models.IntegerField(choices=[(1, 'Buenos Aires'), (2, 'Ciudad Autónoma de Buenos Aires'), (3, 'Catamarca'), (4, 'Chaco'), (5, 'Chubut'), (6, 'Córdoba'), (7, 'Corrientes'), (8, 'Entre Ríos'), (9, 'Formosa'), (10, 'Jujuy'), (11, 'Salta'), (12, 'Tucumán'), (13, 'La Pampa'), (14, 'La Rioja'), (15, 'San Juan'), (16, 'Mendoza'), (17, 'Misiones'), (18, 'Neuquén'), (19, 'Río Negro'), (20, 'San Luis'), (21, 'Santa Cruz'), (22, 'Santa Fé'), (23, 'Santiago del Estero'), (24, 'Tierra del Fuego')]),
        ),
    ]
