# Generated by Django 3.2.18 on 2023-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_season_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
