# Generated by Django 3.2.18 on 2023-06-15 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_guest_duplicated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='duplicated',
            new_name='is_saved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
