# Generated by Django 3.2.18 on 2023-05-23 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20230519_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagemultiple', models.ImageField(upload_to='imagenes/')),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsitesImageMultiple', to='administracion.campsite')),
            ],
            options={
                'db_table': 'ImagenesMultiples',
            },
        ),
    ]
