# Generated by Django 3.2.18 on 2023-06-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20230615_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='administracion.campsite'),
        ),
    ]
