# Generated by Django 3.2.18 on 2023-05-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='campsite',
        ),
        migrations.AddField(
            model_name='campsite',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='campsitesimages', to='administracion.Image'),
        ),
    ]
