# Generated by Django 3.2.18 on 2023-05-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20230523_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='images',
        ),
        migrations.AddField(
            model_name='campsite',
            name='images',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='naturalpark',
            name='image',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
