# Generated by Django 3.2.18 on 2023-05-24 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20230523_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='images',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imagenes/')),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='administracion.campsite')),
            ],
        ),
    ]
