# Generated by Django 3.2.18 on 2023-05-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20230524_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='images',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='campsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsiteimages', to='administracion.campsite'),
        ),
    ]
